version: '2'
services:
  ovpn:
    image: keepl/ovpn
    container_name: ovpn
    volumes:
      - '/opt/docker-openvpn/app/ovpn-data:/etc/openvpn'
      - '/opt/docker-openvpn/utils/timezone:/etc/timezone'
    environment:
      TZ: 'America/Sao_Paulo'
    restart: unless-stopped
    ports:
      - "3000:1194/udp"
    cap_add:
      - "NET_ADMIN"
    networks:
      app_net:
        ipv4_address: 10.0.81.10

networks:
  app_net:
    external:
      name: app_net
